### ISSUE TITLE
Status codes not meaningful

### ISSUE THREAD

**Issue by bradisbell** [sequelize/sequelize-restful#18]
When making GET requests and no data is found, a `200` status code is still returned.

```
/api/Widgets/12345
```

```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 30
ETag: W/"1e-cd5717cc"
Date: Fri, 02 Jan 2015 00:51:34 GMT
Connection: keep-alive

{"status":"success","data":{}}
```

Error responses also return a `200` status code.

```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 100
ETag: W/"64-3af5db98"
Date: Fri, 02 Jan 2015 00:50:46 GMT
Connection: keep-alive

{"status":"error","message":"Wrong association or some unknown DAOFactory: Foos and/or Bars"}
```

**Comment by sdepold** [comment]
Hi @bradisbell,

while I will happily accept and merge pull requests, I no longer continue developing this module.
So you can either provide a pull request, which fixes the behavior or take a closer look at https://github.com/dchester/epilogue.

Best, 
Sascha.
