### ISSUE TITLE
ACL Integration

### ISSUE THREAD

**Issue by yotamsha** [sequelize/sequelize-restful#3]
Hi,
This is not really an issue, but I would like to implement an ACL mechanism
with sequelize-restful. At first I though about doing it with middlewares, but I didn't find a way to integrate it. Right now I'm writing something on my own for this.
Do you have any suggestions about how to implement this?
Thanks.

**Comment by bradisbell** [comment]
+1  A simple hook mechanism would be great, and could serve the purpose of ACLs and others.  Middleware isn't really a good option since you would have to find a way to inspect the resulting data before it was sent to the client.

**Comment by sdepold** [comment]
Hi,

while I will happily accept and merge pull requests, I no longer continue developing this module.
So you can either provide a pull request, which fixes the behavior or take a closer look at https://github.com/dchester/epilogue.

Best, 
Sascha.
